<a href="https://colab.research.google.com/github/williambrunos/Introduction-To-ML/blob/main/Class_5/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow

- Developed by Google Brain;
- Ideal for numerical processing;
- Runs on CPU and GPU;

![TF](https://th.bing.com/th/id/OIP.wB175DvEMQU59qjS5KBSowHaDj?w=347&h=167&c=7&r=0&o=5&pid=1.7)

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [6]:
print(f'Shape of train images: {train_images.shape}')
print(f'Number of train images: {len(train_images)}')
print(f'Number of train labels: {len(train_labels)}')

print(f'Shape of train images: {test_images.shape}')
print(f'Number of train images: {len(test_images)}')
print(f'Number of train labels: {len(test_labels)}')

print(f'Possible labels for images: {np.unique(train_labels)}')

Shape of train images: (60000, 28, 28)
Number of train images: 60000
Number of train labels: 60000
Shape of train images: (10000, 28, 28)
Number of train images: 10000
Number of train labels: 10000
Possible labels for images: [0 1 2 3 4 5 6 7 8 9]


As we can see in the first and in the fourth line, our images have a 28 X 28 pixels size. It's pretty bad that we train a neural network with the images without some preprocessing, because each pixel stores values between 0 and 255, which is bad for gradient oprtimizers. Because of that, it is common to preprocess those pixels dividing them by 255:

In [7]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [12]:
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28, 28)),
                          keras.layers.Dense(128, activation=tf.nn.relu),
                          keras.layers.Dense(10, activation=tf.nn.softmax)
                          ])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [16]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3753 - accuracy: 0.8652
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3367 - accuracy: 0.8775
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3115 - accuracy: 0.8843
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2943 - accuracy: 0.8903
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2818 - accuracy: 0.8953


In [17]:
test_loss, test_acc = model.evaluate(test_images, test_labels) 

print(f'Model accucary for test images: {test_acc}')

313/313 [==============================] - 1s 2ms/step - loss: 0.3436 - accuracy: 0.8795
Model accucary for test images: 0.8794999718666077


In [26]:
predictions = model.predict(test_images)
print(predictions)

[[5.11758390e-06 3.22459948e-09 5.06025373e-08 ... 4.40021530e-02
  6.56151169e-05 9.52990592e-01]
 [4.39020369e-04 4.57479844e-12 9.95896101e-01 ... 6.72170924e-14
  1.42293729e-07 3.45022032e-14]
 [9.98004680e-07 9.99998808e-01 5.51607149e-10 ... 9.30115365e-17
  3.29728172e-12 1.03234495e-14]
 ...
 [2.73745763e-03 3.48564910e-09 1.36817805e-04 ... 3.79152169e-07
  9.95992780e-01 8.81669848e-10]
 [5.32342938e-07 9.99988794e-01 1.11030285e-09 ... 5.77883314e-12
  8.12079914e-09 3.61025706e-12]
 [1.96039167e-04 6.08503979e-05 1.87625381e-04 ... 8.05664584e-02
  5.11506423e-02 3.01110267e-04]]


In [27]:
predictions = np.argmax(predictions, axis=1)
predictions = predictions.reshape(-1, 1)
print(predictions)

[[9]
 [2]
 [1]
 ...
 [8]
 [1]
 [5]]


In [28]:
print(predictions.shape)

(10000, 1)


In [30]:
print(test_labels.reshape(-1, 1))

[[9]
 [2]
 [1]
 ...
 [8]
 [1]
 [5]]


In [31]:
error = predictions - test_labels.reshape(-1, 1)
error

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [32]:
non_zero_errors = [i for i in error if i != 0]
len(non_zero_errors)

1205

In [34]:
print(f'Accuracy of {(10000 - 1205) / 10000 * 100}')

Accuracy of 87.94999999999999
